application: osspoints
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  login: required
  static_dir: js

- url: /css
  login: required
  static_dir: css

- url: /mypoints
  login: required
  script: main.py

- url: /addpoints
  login: admin
  script: main.py

- url: /.*
  login: required
  script: main.py
